---
title: "Microbioma_del_pozol"
---

**Taller de Análisis de Metagenomas, Reconstrucción de Genomas y Análisis de Amplicones.**

En este taller introductorio aprenderemos a organizar un proyecto, analizar y visualizar datos metagenómicos; reconstruir genomas a partir de metagenomas (**MAGs**), a clasificar los MAGs taxonómicamente y a predecir sus genes e inferir su metabolismo. Además, abordaremos un poco sobre el análisis de amplicones del gene 16S ARNr.

------------------------------------------------------------------------

## Temario

Los días 1 y 2 serán de introducción a bash, R y metagenómica. Se seguirá la lección de metagenómica de [Software Carpentry](https://carpentries-lab.github.io/metagenomics-workshop/) que cubre los siguientes puntos:

-   Organización de un proyecto metagenómico: [link](https://carpentries-incubator.github.io/organization-metagenomics/)

-   Introducción a la línea de comandos: [link](https://carpentries-incubator.github.io/shell-metagenomics/)

-   Introducción a R: [link](https://carpentries-incubator.github.io/introduction-to-R-for-metagenomics/)

-   Procesamiento y visualización de datos metagenómicos: [link](https://carpentries-incubator.github.io/metagenomics/)

Los días 3 y 4 Nos enfocaremos en la reconstrucción de MAGs y su inferencia taxonómica y funcional. El día 5 abordaremos el análisis de amplicones. El material para los días 3-5 se encuentra en esta página.

**Día 3**

| Hora          | Tema                      |
|---------------|---------------------------|
| 9:00 - 9:30   | Reconstrucción de genomas |
| 9:30 - 9:50   | ¿Qué es el *binning*?     |
| 9:50 - 10:00  | Descanso                  |
| 10:00 - 12:15 | Reconstrucción de genomas |
| 12:15 - 12:30 | Descanso                  |
| 12:30 - 13:30 | Desreplicación            |
| 13:30 - 14:00 | Discusión de resultados   |
| 14:00 - 15:30 | Comida                    |
| 15:30 - 16:00 | Ejercicio por equipo      |
| 16:00 - 17:00 | Discusión de resultados   |

**Día 4**

| Hora          | Tema                                                    |
|---------------|---------------------------------------------------------|
| 9:00 - 10:00  | Clasificación taxonómica                                |
| 10:00 - 10:45 | Predicción génica                                       |
| 10:45 - 11:00 | Descanso                                                |
| 11:00 - 11:30 | Plática sobre el microbioma del chinicuil               |
| 10:30 - 10:45 | Descanso                                                |
| 10:45 - 12:00 | Rbims                                                   |
| 12:00 - 12:15 | Descanso                                                |
| 12:15 - 14:00 | Otras inferencias metabólicas y discusión de resultados |
| 14:00 - 15:30 | Comida                                                  |
| 15:30 - 17:00 | Vistazo a la reconstrucción viral y eucariótica         |

**Día 5**

| Hora          | Tema                                                      |
|------------------|------------------------------------------------------|
| 9:00 - 10:00  | Introducción al análisis de amplicones                    |
| 10:00 - 10:30 | Introducción a QIIME2                                     |
| 10:30 - 10:45 | Descanso                                                  |
| 10:45 - 12:00 | Importación de datos e inferencia de ASVs                 |
| 12:00 - 12:15 | Descanso                                                  |
| 12:15 - 14:00 | Asignación taxonómica, limpieza e inferencia filogenética |
| 14:00 - 15:30 | Comida                                                    |
| 15:30 - 17:00 | Importación a R, gráficos y diversidad                    |
