---
title: "Preparemos todo para el proyecto"
---

::: callout-tip
## Reglas del juego

-   **En este tutorial haremos el ejemplo corriendo la muestra de 48 hrs.**

-   **Se formaran 6 equipos (2 de los tiempos 0, 9 y 24 hrs).**

-   **Los equipos discutir치n y presentar치n sus resultados.**
:::

## Espacio de trabajo

1.  Entra a tu cuenta en el servidor y sit칰ate en tu `$HOME`

2.  Obten los datos y la estructura de tu directorio del proyecto clonando el siguiente repositorio:

``` bash
git clone https://github.com/DianaOaxaca/taller_metagenomica_pozol.git
```

3.  Entra al directorio y descomprime el ensamble y el archivo de profundidad de la muestra de 48 hrs:

``` bash
cd taller_metagenomica_pozol
gunzip results/02.ensambles/48hrs.fasta.gz
gunzip results/03.profundidad/48hrs.mgh_depth.txt.gz
```

4.  Entra al directorio del proyecto

``` bash
cd taller_metagenomica_pozol
```

<p align="justify">

<FONT COLOR="darkblue">La presente pr치ctica s칩lo es una representaci칩n del flujo de trabajo para el an치lisis metagen칩mico, sin embargo, no sustituye los manuales de cada programa y el flujo puede variar dependiendo del tipo de datos y pregunta de investigaci칩n, de hecho para fines del taller, con frecuencia se utilizan las lineas de comando m치s simples para eficientar tiempo y recursos, t칩malo en cuenta.</FONT>

</p>

Cada programa tiene una ayuda y un manual de usuario, es **importante** revisarlo y conocer cada par치metro que se ejecute. En terminal se puede consultar el manual con el comando `man` y tambi칠n se puede consultar la ayuda con `-h` o `--help`, por ejemplo `fastqc -h`.

::: callout-important
游 Para tenerlo presente

En bioinform치tica cualquier l칤nea de comandos generar치 un resultado, de ah칤 a que esos resultados sean correctos puede haber una gran diferencia.

En cada paso detente a revisar la informaci칩n de cada programa, lee el manual, visita foros de ayuda y selecciona los argumentos que se ajusten a las necesidades de tus datos.
:::
